Search.appendIndex(
    [
                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface",
            "name": "ValidatorEngineInterface",
            "summary": "Interface\u0020for\u0020validator\u0020engine.\u0020You\u0020can\u0020use\u0020different\u0020engines,\nthat\u0020implements\u0020ValidatorEngineInterface\nSo,\u0020for\u0020use\u0020validator,\u0020you\u0020must\u0020create\u0020ValidatorInterface\u0020and\u0020inject\ninto\u0020it\u0020ValidatorFactoryInterface\u0020\u0028as\u0020in\u0020ValidatorFactory\u0029.",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003Avalidate_required\u0028\u0029",
            "name": "validate_required",
            "summary": "Validate\u0020for\u0020required\u0020field\nUsage\u003A\u0020required",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_validate_required"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003Avalidate_notempty\u0028\u0029",
            "name": "validate_notempty",
            "summary": "Validate\u0020if\u0020not\u0020empty\nUsage\u003A\u0020notempty",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_validate_notempty"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003Avalidate_min\u0028\u0029",
            "name": "validate_min",
            "summary": "Validate\u0020min\u0020numeric\nUsage\u003A\u0020min\u003A3\u007Cmax\u003A10",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_validate_min"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003Avalidate_numeric\u0028\u0029",
            "name": "validate_numeric",
            "summary": "Validate\u0020if\u0020value\u0020is\u0020numeric\nUsage\u003A\u0020numeric",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_validate_numeric"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003Avalidate_max\u0028\u0029",
            "name": "validate_max",
            "summary": "Validate\u0020for\u0020max\u0020value\nUsage\u003A\u0020min\u003A10\u007Cmax\u003A20",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_validate_max"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003Avalidate_minlength\u0028\u0029",
            "name": "validate_minlength",
            "summary": "Validate\u0020for\u0020minimum\u0020length\u0020in\u0020strings\nUsage\u003A\u0020maxlength\u003A100",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_validate_minlength"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003Avalidate_maxlength\u0028\u0029",
            "name": "validate_maxlength",
            "summary": "Validate\u0020for\u0020maximum\u0020length\u0020in\u0020strings\nUsage\u003A\u0020minlength\u003A10",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_validate_maxlength"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003Avalidate_email\u0028\u0029",
            "name": "validate_email",
            "summary": "Validate\u0020for\u0020email\nUsage\u003A\u0020email\u0020or\u0020email\u007Crequired",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_validate_email"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003Avalidate_email_dns\u0028\u0029",
            "name": "validate_email_dns",
            "summary": "Deep\u0020validation\u0020of\u0020email\nUsage\u003A\u0020validate_email_dns",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_validate_email_dns"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003Avalidate_url\u0028\u0029",
            "name": "validate_url",
            "summary": "Valudate\u0020url\nUsage\u003A\u0020url",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_validate_url"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003Avalidate_url_active\u0028\u0029",
            "name": "validate_url_active",
            "summary": "Validate\u0020for\u0020active\u0020url\nUsage\u003A\u0020url_active",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_validate_url_active"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003Avalidate_date\u0028\u0029",
            "name": "validate_date",
            "summary": "Validate\u0020for\u0020date",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_validate_date"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003Avalidate_date_format\u0028\u0029",
            "name": "validate_date_format",
            "summary": "Validate\u0020for\u0020date\u0020in\u0020some\u0020format",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_validate_date_format"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003Avalidate_date_before\u0028\u0029",
            "name": "validate_date_before",
            "summary": "Validate\u0020if\u0020date\u0020before\u0020date",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_validate_date_before"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003Avalidate_date_after\u0028\u0029",
            "name": "validate_date_after",
            "summary": "Validate\u0020for\u0020date\u0020after\u0020date",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_validate_date_after"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003Avalidate_boolean\u0028\u0029",
            "name": "validate_boolean",
            "summary": "Validate\u0020for\u0020boolean",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_validate_boolean"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003AsetError\u0028\u0029",
            "name": "setError",
            "summary": "Set\u0020new\u0020validator\u0020error",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_setError"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "Set\u0020field\u0020name",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_setName"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003AsetNames\u0028\u0029",
            "name": "setNames",
            "summary": "Set\u0020field\u0020names",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_setNames"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003AclearNames\u0028\u0029",
            "name": "clearNames",
            "summary": "Reset\u0020names",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_clearNames"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003AclearMessages\u0028\u0029",
            "name": "clearMessages",
            "summary": "Reset\u0020messages",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_clearMessages"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorEngineInterface\u003A\u003AgetMessages\u0028\u0029",
            "name": "getMessages",
            "summary": "Get\u0020validation\u0020messages",
            "url": "classes/Core-Interfaces-ValidatorEngineInterface.html#method_getMessages"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorFactoryInterface",
            "name": "ValidatorFactoryInterface",
            "summary": "This\u0020is\u0020factory\u0020that\u0020create\u0020configured\u0020validator\u0020object",
            "url": "classes/Core-Interfaces-ValidatorFactoryInterface.html"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorFactoryInterface\u003A\u003AgetValidator\u0028\u0029",
            "name": "getValidator",
            "summary": "Get\u0020ready\u002Dto\u002Duse\u0020validator\nBut\u0020you\u0020can\u0020use\u0020own\u0020engine\u0020that\u0020implements\u0020ValidatorEngineInterface",
            "url": "classes/Core-Interfaces-ValidatorFactoryInterface.html#method_getValidator"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorFactoryInterface\u003A\u003AgetValidatorEngine\u0028\u0029",
            "name": "getValidatorEngine",
            "summary": "Get\u0020default\u0020validator\u0020engine",
            "url": "classes/Core-Interfaces-ValidatorFactoryInterface.html#method_getValidatorEngine"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorInterface",
            "name": "ValidatorInterface",
            "summary": "Main\u0020interface\u0020for\u0020validator.",
            "url": "classes/Core-Interfaces-ValidatorInterface.html"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorInterface\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validate\u0020loaded\u0020fields",
            "url": "classes/Core-Interfaces-ValidatorInterface.html#method_validate"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorInterface\u003A\u003AsetIgnored\u0028\u0029",
            "name": "setIgnored",
            "summary": "Set\u0020field\u0020keys\u0020for\u0020ignore",
            "url": "classes/Core-Interfaces-ValidatorInterface.html#method_setIgnored"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorInterface\u003A\u003AsetValues\u0028\u0029",
            "name": "setValues",
            "summary": "Set\u0020field\u0020values",
            "url": "classes/Core-Interfaces-ValidatorInterface.html#method_setValues"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorInterface\u003A\u003AsetValue\u0028\u0029",
            "name": "setValue",
            "summary": "Set\u0020value\u0020for\u0020field",
            "url": "classes/Core-Interfaces-ValidatorInterface.html#method_setValue"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorInterface\u003A\u003AsetRules\u0028\u0029",
            "name": "setRules",
            "summary": "Set\u0020rules",
            "url": "classes/Core-Interfaces-ValidatorInterface.html#method_setRules"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorInterface\u003A\u003AsetRule\u0028\u0029",
            "name": "setRule",
            "summary": "Set\u0020short\u0020rule",
            "url": "classes/Core-Interfaces-ValidatorInterface.html#method_setRule"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorInterface\u003A\u003AsetFullRule\u0028\u0029",
            "name": "setFullRule",
            "summary": "Set\u0020full\u0020rule\u0020for\u0020field",
            "url": "classes/Core-Interfaces-ValidatorInterface.html#method_setFullRule"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorInterface\u003A\u003Areset\u0028\u0029",
            "name": "reset",
            "summary": "Reset\u0020validator\u0020rules\u0020for\u0020next\u0020check",
            "url": "classes/Core-Interfaces-ValidatorInterface.html#method_reset"
        },                {
            "fqsen": "\\Core\\Interfaces\\ValidatorInterface\u003A\u003AgetMessages\u0028\u0029",
            "name": "getMessages",
            "summary": "Get\u0020validator\u0020messages",
            "url": "classes/Core-Interfaces-ValidatorInterface.html#method_getMessages"
        },                {
            "fqsen": "\\Core\\Utils\\Validator",
            "name": "Validator",
            "summary": "",
            "url": "classes/Core-Utils-Validator.html"
        },                {
            "fqsen": "\\Core\\Utils\\Validator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020that\u0020set\u0020validation\u0020engine\u0020and\u0020set\u0020locales",
            "url": "classes/Core-Utils-Validator.html#method___construct"
        },                {
            "fqsen": "\\Core\\Utils\\Validator\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validate\u0020loaded\u0020fields",
            "url": "classes/Core-Utils-Validator.html#method_validate"
        },                {
            "fqsen": "\\Core\\Utils\\Validator\u003A\u003AgetActions\u0028\u0029",
            "name": "getActions",
            "summary": "",
            "url": "classes/Core-Utils-Validator.html#method_getActions"
        },                {
            "fqsen": "\\Core\\Utils\\Validator\u003A\u003AsetIgnored\u0028\u0029",
            "name": "setIgnored",
            "summary": "Set\u0020field\u0020keys\u0020for\u0020ignore",
            "url": "classes/Core-Utils-Validator.html#method_setIgnored"
        },                {
            "fqsen": "\\Core\\Utils\\Validator\u003A\u003AsetValues\u0028\u0029",
            "name": "setValues",
            "summary": "Set\u0020field\u0020values",
            "url": "classes/Core-Utils-Validator.html#method_setValues"
        },                {
            "fqsen": "\\Core\\Utils\\Validator\u003A\u003AsetValue\u0028\u0029",
            "name": "setValue",
            "summary": "Set\u0020value\u0020for\u0020field",
            "url": "classes/Core-Utils-Validator.html#method_setValue"
        },                {
            "fqsen": "\\Core\\Utils\\Validator\u003A\u003AsetRules\u0028\u0029",
            "name": "setRules",
            "summary": "Set\u0020rules",
            "url": "classes/Core-Utils-Validator.html#method_setRules"
        },                {
            "fqsen": "\\Core\\Utils\\Validator\u003A\u003AsetRule\u0028\u0029",
            "name": "setRule",
            "summary": "Set\u0020short\u0020rule",
            "url": "classes/Core-Utils-Validator.html#method_setRule"
        },                {
            "fqsen": "\\Core\\Utils\\Validator\u003A\u003AsetFullRule\u0028\u0029",
            "name": "setFullRule",
            "summary": "Set\u0020full\u0020rule\u0020for\u0020field",
            "url": "classes/Core-Utils-Validator.html#method_setFullRule"
        },                {
            "fqsen": "\\Core\\Utils\\Validator\u003A\u003Areset\u0028\u0029",
            "name": "reset",
            "summary": "Reset\u0020validator\u0020rules\u0020for\u0020next\u0020check",
            "url": "classes/Core-Utils-Validator.html#method_reset"
        },                {
            "fqsen": "\\Core\\Utils\\Validator\u003A\u003AgetMessages\u0028\u0029",
            "name": "getMessages",
            "summary": "Get\u0020validator\u0020messages",
            "url": "classes/Core-Utils-Validator.html#method_getMessages"
        },                {
            "fqsen": "\\Core\\Utils\\Validator\u003A\u003AsetLocales\u0028\u0029",
            "name": "setLocales",
            "summary": "",
            "url": "classes/Core-Utils-Validator.html#method_setLocales"
        },                {
            "fqsen": "\\Core\\Utils\\Validator\u003A\u003A\u0024validators",
            "name": "validators",
            "summary": "This\u0020object\u0020stores\u0020implementations\u0020of\u0020specific\u0020validators\nThey\u0020run\u0020depending\u0020on\u0020the\u0020validation\u0020instructions",
            "url": "classes/Core-Utils-Validator.html#property_validators"
        },                {
            "fqsen": "\\Core\\Utils\\Validator\u003A\u003A\u0024ignored",
            "name": "ignored",
            "summary": "Array\u0020of\u0020ignored\u0020fields\u0020for\u0020validation",
            "url": "classes/Core-Utils-Validator.html#property_ignored"
        },                {
            "fqsen": "\\Core\\Utils\\Validator\u003A\u003A\u0024rules",
            "name": "rules",
            "summary": "Validation\u0020rules\u0020is\u0020an\u0020associative\u0020array\nin\u0020\u0024key\u003D\u003E\u0024value\u0020format\u0020where\u0020key\u0020is\u0020field\u0020name\u0020and\u0020value\u0020is\u0020rule",
            "url": "classes/Core-Utils-Validator.html#property_rules"
        },                {
            "fqsen": "\\Core\\Utils\\Validator\u003A\u003A\u0024values",
            "name": "values",
            "summary": "Values\u0020array,\u0020that\u0020is\u0020an\u0020\u0024key\u003D\u003E\u0024value\u0020associtive\u0020array,\nwhere\u0020\u0024key\u0020is\u0020field\u0020name\u0020and\u0020value\u0020is\u0020field\u0020value",
            "url": "classes/Core-Utils-Validator.html#property_values"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine",
            "name": "ValidatorEngine",
            "summary": "Default\u0020validator\u0020engine",
            "url": "classes/Core-Utils-ValidatorEngine.html"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003Avalidate_required\u0028\u0029",
            "name": "validate_required",
            "summary": "Validate\u0020for\u0020required\u0020field\nUsage\u003A\u0020required",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_validate_required"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003Avalidate_notempty\u0028\u0029",
            "name": "validate_notempty",
            "summary": "Validate\u0020if\u0020not\u0020empty\nUsage\u003A\u0020notempty",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_validate_notempty"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003Avalidate_min\u0028\u0029",
            "name": "validate_min",
            "summary": "Validate\u0020min\u0020numeric\nUsage\u003A\u0020min\u003A3\u007Cmax\u003A10",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_validate_min"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003Avalidate_numeric\u0028\u0029",
            "name": "validate_numeric",
            "summary": "Validate\u0020if\u0020value\u0020is\u0020numeric\nUsage\u003A\u0020numeric",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_validate_numeric"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003Avalidate_max\u0028\u0029",
            "name": "validate_max",
            "summary": "Validate\u0020for\u0020max\u0020value\nUsage\u003A\u0020min\u003A10\u007Cmax\u003A20",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_validate_max"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003Avalidate_minlength\u0028\u0029",
            "name": "validate_minlength",
            "summary": "Validate\u0020for\u0020minimum\u0020length\u0020in\u0020strings\nUsage\u003A\u0020maxlength\u003A100",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_validate_minlength"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003Avalidate_maxlength\u0028\u0029",
            "name": "validate_maxlength",
            "summary": "Validate\u0020for\u0020maximum\u0020length\u0020in\u0020strings\nUsage\u003A\u0020minlength\u003A10",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_validate_maxlength"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003Avalidate_email\u0028\u0029",
            "name": "validate_email",
            "summary": "Validate\u0020for\u0020email\nUsage\u003A\u0020email\u0020or\u0020email\u007Crequired",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_validate_email"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003Avalidate_email_dns\u0028\u0029",
            "name": "validate_email_dns",
            "summary": "Deep\u0020validation\u0020of\u0020email\nUsage\u003A\u0020validate_email_dns",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_validate_email_dns"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003Avalidate_url\u0028\u0029",
            "name": "validate_url",
            "summary": "Valudate\u0020url\nUsage\u003A\u0020url",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_validate_url"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003Avalidate_url_active\u0028\u0029",
            "name": "validate_url_active",
            "summary": "Validate\u0020for\u0020active\u0020url\nUsage\u003A\u0020url_active",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_validate_url_active"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003Avalidate_date\u0028\u0029",
            "name": "validate_date",
            "summary": "Validate\u0020for\u0020date",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_validate_date"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003Avalidate_date_format\u0028\u0029",
            "name": "validate_date_format",
            "summary": "Validate\u0020for\u0020date\u0020in\u0020some\u0020format",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_validate_date_format"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003Avalidate_date_before\u0028\u0029",
            "name": "validate_date_before",
            "summary": "Validate\u0020if\u0020date\u0020before\u0020date",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_validate_date_before"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003Avalidate_date_after\u0028\u0029",
            "name": "validate_date_after",
            "summary": "Validate\u0020for\u0020date\u0020after\u0020date",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_validate_date_after"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003Avalidate_boolean\u0028\u0029",
            "name": "validate_boolean",
            "summary": "Validate\u0020for\u0020boolean",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_validate_boolean"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003AsetError\u0028\u0029",
            "name": "setError",
            "summary": "Set\u0020new\u0020validator\u0020error",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_setError"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "Set\u0020field\u0020name",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_setName"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003AsetNames\u0028\u0029",
            "name": "setNames",
            "summary": "Set\u0020field\u0020names",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_setNames"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003AclearMessages\u0028\u0029",
            "name": "clearMessages",
            "summary": "Reset\u0020messages",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_clearMessages"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003AclearNames\u0028\u0029",
            "name": "clearNames",
            "summary": "Reset\u0020names",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_clearNames"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003AgetMessages\u0028\u0029",
            "name": "getMessages",
            "summary": "Get\u0020validation\u0020messages",
            "url": "classes/Core-Utils-ValidatorEngine.html#method_getMessages"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003A\u0024names",
            "name": "names",
            "summary": "Labels\u0020\u0028human\u002Dreadable\u0029\u0020for\u0020use\u0020in\u0020error\u0020output",
            "url": "classes/Core-Utils-ValidatorEngine.html#property_names"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003A\u0024messages",
            "name": "messages",
            "summary": "Validation\u0020messages\u0020array",
            "url": "classes/Core-Utils-ValidatorEngine.html#property_messages"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorEngine\u003A\u003A\u0024allowedUrl",
            "name": "allowedUrl",
            "summary": "This\u0020is\u0020for\u0020validate\u0020URL",
            "url": "classes/Core-Utils-ValidatorEngine.html#property_allowedUrl"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorFactory",
            "name": "ValidatorFactory",
            "summary": "Validator\u0020factory\u0020that\u0020create\u0020ready\u002Dfor\u002Duse\u0020validator\u0020object",
            "url": "classes/Core-Utils-ValidatorFactory.html"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorFactory\u003A\u003AgetValidator\u0028\u0029",
            "name": "getValidator",
            "summary": "Get\u0020ready\u002Dto\u002Duse\u0020validator\nBut\u0020you\u0020can\u0020use\u0020own\u0020engine\u0020that\u0020implements\u0020ValidatorEngineInterface",
            "url": "classes/Core-Utils-ValidatorFactory.html#method_getValidator"
        },                {
            "fqsen": "\\Core\\Utils\\ValidatorFactory\u003A\u003AgetValidatorEngine\u0028\u0029",
            "name": "getValidatorEngine",
            "summary": "Get\u0020default\u0020validator\u0020engine",
            "url": "classes/Core-Utils-ValidatorFactory.html#method_getValidatorEngine"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Core\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/core-interfaces.html"
        },                {
            "fqsen": "\\Core",
            "name": "Core",
            "summary": "",
            "url": "namespaces/core.html"
        },                {
            "fqsen": "\\Core\\Utils",
            "name": "Utils",
            "summary": "",
            "url": "namespaces/core-utils.html"
        }            ]
);
